<?php

namespace Souk\BackBundle\Repository;

/**
 * CommentairesEvsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairesEvsRepository extends \Doctrine\ORM\EntityRepository
{
}
