<?php

namespace Souk\BackBundle\Repository;

/**
 * CommentairesAncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairesAncRepository extends \Doctrine\ORM\EntityRepository
{
}
