<?php

namespace Souk\BackBundle\Repository;

/**
 * EvennementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvennementsRepository extends \Doctrine\ORM\EntityRepository
{
}
