<?php

namespace Souk\BackBundle\Repository;

/**
 * HistoriqueAbsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueAbsRepository extends \Doctrine\ORM\EntityRepository
{
}
