<?php

namespace Souk\BackBundle\Repository;

/**
 * SignalsEvsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalsEvsRepository extends \Doctrine\ORM\EntityRepository
{
}
