<?php

namespace Souk\BackBundle\Repository;

/**
 * SignalsAncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalsAncRepository extends \Doctrine\ORM\EntityRepository
{
}
