<?php

namespace Proxies\__CG__\Souk\BackBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evennements extends \Souk\BackBundle\Entity\Evennements implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'id', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'titre', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'description', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'dateDeb', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'dateFin', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'lieu', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'prix', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'commentaires', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'client', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'commercial', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'reservations', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'signals'];
        }

        return ['__isInitialized__', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'id', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'titre', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'description', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'dateDeb', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'dateFin', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'lieu', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'prix', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'commentaires', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'client', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'commercial', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'reservations', '' . "\0" . 'Souk\\BackBundle\\Entity\\Evennements' . "\0" . 'signals'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evennements $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSignalsEvs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignalsEvs', []);

        return parent::getSignalsEvs();
    }

    /**
     * {@inheritDoc}
     */
    public function getReservations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservations', []);

        return parent::getReservations();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommercial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommercial', []);

        return parent::getCommercial();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommercial($commercial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommercial', [$commercial]);

        return parent::setCommercial($commercial);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient($client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', []);

        return parent::getCommentaires();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeb($dateDeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeb', [$dateDeb]);

        return parent::setDateDeb($dateDeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeb', []);

        return parent::getDateDeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin($dateFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$dateFin]);

        return parent::setDateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieu($lieu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieu', [$lieu]);

        return parent::setLieu($lieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieu', []);

        return parent::getLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

}
